-- Create new data table
-- Create the main table used to import the original CSV file.

CREATE TABLE sales_data(
	transaction_type TEXT,
	days_for_shipping INTEGER,
	days_for_shipment INTEGER,
	benefit_per_order NUMERIC(10,2),
	sales_per_customer NUMERIC(10,2),
	delivery_status TEXT,
	late_delivery_risk INTEGER,
	category_id INTEGER,
	category_name TEXT,
	customer_city TEXT,
	customer_country TEXT,
	customer_email TEXT,
	customer_fname TEXT,
	customer_id INTEGER,
	customer_lname TEXT,
	customer_password TEXT,
	customer_segment TEXT,
	customer_state TEXT,
	customer_street TEXT,
	customer_zipcode VARCHAR(20),
	department_id INTEGER,
	department_name TEXT,
	latitude NUMERIC(10,6),
	longitude NUMERIC(10,6),
	market TEXT,
	order_city TEXT,
	order_country TEXT,
	order_customer_id INTEGER,
	order_date TIMESTAMP,
	order_id INTEGER,
	order_item_cardprod_id INTEGER,
	order_item_discount NUMERIC(10,2),
	order_item_discount_rate NUMERIC(5,2),
	order_item_id INTEGER,
	order_item_product_price NUMERIC(10,2),
	order_item_profit_ratio NUMERIC(10,2),
	order_item_quantity INTEGER,
	sales NUMERIC(10,2),
	order_item_total NUMERIC(10,2),
	order_profit_per_order NUMERIC(10,2),
	order_region TEXT,
	order_state TEXT,
	order_status TEXT,
	order_zipcode VARCHAR(20),
	product_card_id INTEGER,
	product_category_id INTEGER,
	product_description TEXT,
	product_image TEXT,
	product_name TEXT,
	product_price NUMERIC(10,2),
	product_status INTEGER,
	shipping_date TIMESTAMP,
	shipping_mode TEXT
);